---
# vars file for aap
aap_local_installer_path: "/path_to/ansible-automation-platform-containerized-setup-2.6-4.tar.gz" # local path to the AAP setup file
# aap_base_dir: "/home/ec2-user" # path to the ansible related file uploaded for AWS
aap_base_dir: "/data" # path to the ansible related file uploaded for Azure
aap_installer_dest_path: "ansible-automation-platform-containerized-setup-2.6-4" # extracted directory name corresponding to the AAP setup file
